mod 'brwyatt/ceph', :git => 'https://github.com:brwyatt/puppet-ceph'
mod 'camptocamp/augeas', '1.4.2'
mod 'camptocamp/kmod', '2.1.0'
mod 'gardouille/megacli', '0.2.1'
mod 'gdsoperations/resolvconf', '0.3.3'
mod 'puppetlabs/apt', '2.2.1'
mod 'puppetlabs/concat', '2.1.0'
mod 'puppetlabs/firewall', '1.7.2'
mod 'puppetlabs/inifile', '1.4.3'
mod 'puppetlabs/stdlib', '4.11.0'
mod 'trepasi/debnet', '1.5.2'
